### ISSUE TITLE
Algunas mejoras

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-2-evaluacion-intermedia-Nanakuh#2]
Muy buen trabajo @Nanakuh !!!

Te propongo...

### Otros retos que van más allá

Ahora (o, mejor, cuando acabe el curso) puedes mejorar el juego a tu gusto, aquí tienes algunas ideas:

- Añade un botón de reinicio que limpie el contador de intentos, genere un nuevo número aleatorio y escriba el feedback inicial. 
- Muestra el botón de reiniciar el juego cuando el juego se haya terminado y oculta el botón de prueba. 
- Completa el código necesario para que funcione el botón de reinicio. 
- Añade un límite para el número de intentos. Si la usuaria alcanza ese límite, la página anuncia que "El juego ha terminado". 
- Lo que se te ocurra.

### Call to action

Avísame si tienes alguna duda ;)

¡A por ello!

> A partir de ahora puedes confirmar tus cambios en la rama principal de tu proyecto.
> Puedes cerrar este issue cuando lo consideres oportuno.

**Comment by Nanakuh** [comment]
Hola Iván, muchas gracias por las ideas para hacer el juego más avanzado, puedes estar seguro que intentaré implementar esos cambios cuando acabemos.

**Comment by igarrido-adalab** [comment]
Según está ahora mismo, esta ev. intermedia está perfecta!
